services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      - app-network

  app1:
    image: php:7.4-apache #nginx:alpine
    volumes:
      - .server_info.php:/usr/share/nginx/index.php
    networks:
      - app-network

  app2:
    image: php:7.4-apache #nginx:alpine
    volumes:
      - .server_info.php:/usr/share/nginx/index.php
    networks:
      - app-network

  app3:
    image: php:7.4-apache #nginx:alpine
    volumes:
      - .server_info.php:/usr/share/nginx/index.php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge